//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoCaro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Play
    {
        public string Name { get; set; }
        public Nullable<int> wins { get; set; }
        public Nullable<int> loses { get; set; }
    }
}
